name: vital_app
description: "A Vital Signs Monitoring App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  drift: ^2.18.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_blue_plus: ^1.32.4
  freezed_annotation: ^2.4.1
  mqtt_client: ^10.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3: ^2.4.2
  sqlite3_async: ^1.0.4
  sqlite3_flutter_libs: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  icons_launcher: ^2.1.7
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/emqxsl-ca.crt
